"""Off `high` — max-anchored geometric ladder (Keno Xtreme Hard / Degen).

Same algorithm as Off `classic` (`easy_off_classic.generate_classic_row`):
lock the designed max, keep the HUD zero prefix, fill the body with a
constant-ratio ladder onto RTP 0.9650, snap to the 0.1x lattice, repair.

HUD picks 2–6 are player-favor (pick 3 at 500x is ~614% RTP). luma-keno
must not paste those tops. Highest in-window / gate-legal maxes:

- Pick 2: HUD 20.00 with a two-zero prefix is 1.1538 RTP. Only 16.7 sits
  in-window (16.7 * P(2) = 0.96346). Single paying cell — Hard identity.
- Pick 3: HUD 500 blows RTP and ETL40. Highest lattice-legal is 71.6
  (etl40 0.870 vs local 0.88).
- Pick 4: HUD 1000 rejects; highest legal is 382.4 (etl40 0.879).
- Pick 5: HUD 2500 rejects on ETL40; the std-18.3 envelope (HIGH, not
  EXTREME) binds first at 900 (2297.8 was std 45).
- Picks 6–8: HUD 6000 / 12500 / 25000 are the same EXTREME peak
  (P(k)·M² still moves variance). Caps 2200 / 5500 / 6100 land std
  18.2 / 18.1 / 10.0. Pick 8's jackpot is already too rare for a
  HIGH label at any max under the Extreme boundary.
- Picks 9–10 keep the HUD tops (40000 / 50000). Those cells have
  almost no part in variance (top share ~19% / ~2.5%); labels stay
  HIGH / MEDIUM. Do not cut them to chase a label.

pick_1 stays lattice pick_one_row("high") = [0.1, 3.5] with the miss-bonus
third tier (high is in PICK_ONE_BONUS_RISKS).

Scope: **Off only.** Earn `high` and the buy chips keep their own ladders.
"""

from __future__ import annotations

from fractions import Fraction

from easy_off_classic import generate_classic_row
from keno_pick_one import MODE_RTP_BAND, STD_MIN, base_coeff, base_stats

RTP_WINDOW = (0.9630, 0.9655)
ETL40_CAP = 0.88
CVAR_CAP = 700.0
# Dashboard Extreme sits in (18.3, 25.73]. Picks 5–8 must stay under it.
STD_LABEL_CAP = 18.5
STD_LABEL_PICKS = frozenset({5, 6, 7, 8})

#: Competitor Hard HUD rows: zeros/shape template only.
HIGH_HUD = {
    2: [0.00, 0.00, 20.00],
    3: [0.00, 0.00, 0.50, 500.0],
    4: [0.00, 0.00, 0.00, 1.50, 1000.0],
    5: [0.00, 0.00, 0.00, 0.50, 25.00, 2500.0],
    6: [0.00, 0.00, 0.00, 0.25, 1.50, 350.0, 6000.0],
    7: [0.00, 0.00, 0.00, 0.10, 0.50, 3.00, 950.0, 12500.0],
    8: [0.00, 0.00, 0.00, 0.10, 0.50, 1.50, 40.00, 1500.0, 25000.0],
    9: [0.00, 0.00, 0.00, 0.10, 0.30, 0.50, 5.00, 40.00, 3500.0, 40000.0],
    10: [0.00, 0.00, 0.00, 0.10, 0.30, 0.50, 1.50, 3.00, 90.00, 4500.0, 50000.0],
}

#: Designed max ladder. Strictly increasing from pick_1 lattice max 3.5.
#: Picks 2–4 cannot take the HUD tops (RTP / ETL40 / generator reject).
#: Picks 5–8 sit on the std-18.3 envelope so the dashboard stays HIGH,
#: not EXTREME. Picks 9–10 keep the Hard headlines.
MAX_LADDER = {
    2: 16.7,
    3: 71.6,
    4: 382.4,
    5: 900.0,
    6: 2200.0,
    7: 5500.0,
    8: 6100.0,
    9: 40000.0,
    10: 50000.0,
}

#: Geometric lock replaces the restair `shape_lock` for this chart.
SHAPE_LOCKED: frozenset[int] = frozenset(range(2, 11))


def generate_high_row(k: int) -> list[float]:
    return generate_classic_row(k, HIGH_HUD[k], MAX_LADDER[k])


def generate_high_off() -> dict[int, list[float]]:
    return {k: generate_high_row(k) for k in sorted(HIGH_HUD)}


#: Shipped Off `high` chart (picks 2-10). Generated by the max-anchored
#: geometric ladder onto 0.9650. Pick 2 is a single-cell jackpot:
#: 16.7 * P(2) = 0.963462 is the only in-window lattice point.
HIGH_OFF: dict[int, list[float]] = {
    2: [0.0, 0.0, 16.7],
    3: [0.0, 0.0, 0.7, 71.6],
    4: [0.0, 0.0, 0.0, 2.2, 382.4],
    5: [0.0, 0.0, 0.0, 2.3, 45.7, 900.0],
    6: [0.0, 0.0, 0.0, 1.2, 14.3, 178.7, 2200.0],
    7: [0.0, 0.0, 0.0, 0.6, 6.2, 59.1, 570.4, 5500.0],
    8: [0.0, 0.0, 0.0, 0.6, 3.8, 23.9, 152.0, 964.2, 6100.0],
    9: [0.0, 0.0, 0.0, 0.2, 1.6, 11.7, 90.8, 690.2, 5252.2, 40000.0],
    10: [0.0, 0.0, 0.0, 0.2, 1.2, 6.7, 40.2, 240.3, 1424.6, 8436.9, 50000.0],
}


def _exact_rtp(k: int, row: list[float]) -> Fraction:
    return sum(coeff * Fraction(str(m)) for coeff, m in zip(base_coeff(k), row))


def _validate() -> None:
    generated = generate_high_off()
    prev_max = 3.5  # high pick_1 lattice max
    for k, row in sorted(HIGH_OFF.items()):
        hud = HIGH_HUD[k]
        assert row == generated[k], (
            f"pick_{k}: baked HIGH_OFF {row} != generator {generated[k]}"
        )
        assert len(row) == k + 1, f"pick_{k}: row length {len(row)} != {k + 1}"
        for h, m in enumerate(row):
            assert m == 0.0 or abs(m * 10 - round(m * 10)) < 1e-9, (
                f"pick_{k} h={h}: {m} is off the 0.1x lattice"
            )
        assert [m == 0 for m in row] == [m == 0 for m in hud], (
            f"pick_{k}: zero prefix diverges from the Hard HUD shape"
        )
        paying = [m for m in row if m > 0]
        assert all(b > a for a, b in zip(paying, paying[1:])), (
            f"pick_{k}: ladder is not strictly increasing: {row}"
        )
        expected_max = MAX_LADDER[k]
        assert max(row) == expected_max, (
            f"pick_{k}: max {max(row)} != designed max {expected_max}"
        )
        assert max(row) > prev_max, (
            f"pick_{k}: max {max(row)} does not exceed previous max {prev_max}"
        )
        prev_max = max(row)
        rtp = _exact_rtp(k, row)
        lo, hi = MODE_RTP_BAND
        assert lo < rtp < hi, f"pick_{k}: rtp {float(rtp):.6f} outside band"
        assert RTP_WINDOW[0] <= rtp <= RTP_WINDOW[1], (
            f"pick_{k}: rtp {float(rtp):.6f} outside designed window "
            f"{RTP_WINDOW[0]:.4f}-{RTP_WINDOW[1]:.4f}"
        )
        stats = base_stats(k, row)
        assert stats["std"] >= STD_MIN, (
            f"pick_{k}: std {stats['std']:.3f} < {STD_MIN} (Base Mode STD floor)"
        )
        assert stats["hit_rate"] >= 0.021, f"pick_{k}: hit rate below 1 in 50"
        assert stats["etl_sum"] <= 1.45, f"pick_{k}: etl_sum over the 3-Star gate"
        assert stats["etl40"] <= ETL40_CAP, (
            f"pick_{k}: etl40 {stats['etl40']:.3f} over {ETL40_CAP}"
        )
        assert stats["cvar"] <= CVAR_CAP, (
            f"pick_{k}: cvar {stats['cvar']:.1f} over {CVAR_CAP}"
        )
        if k in STD_LABEL_PICKS:
            assert stats["std"] <= STD_LABEL_CAP, (
                f"pick_{k}: std {stats['std']:.3f} over {STD_LABEL_CAP} "
                "(dashboard Extreme band)"
            )


_validate()


def high_off_summary() -> str:
    lines = []
    for k, row in sorted(HIGH_OFF.items()):
        cells = " / ".join(f"{m:g}" for m in row if m > 0)
        rtp = float(_exact_rtp(k, row))
        stats = base_stats(k, row)
        pay = [m for m in row if m > 0]
        ratios = [b / a for a, b in zip(pay, pay[1:])]
        step = f"{min(ratios):.2f}-{max(ratios):.2f}" if ratios else "-"
        p_top = base_coeff(k)[k]
        top_share = (
            p_top * (max(row) - rtp) ** 2 / stats["std"] ** 2 if stats["std"] else 0
        )
        lines.append(
            f"high_pick_{k:<2d} [{cells}] "
            f"rtp={rtp:.6f} edge={1 - rtp:.4%} "
            f"std={stats['std']:.3f} topShare={top_share:.1%} "
            f"etl40={stats['etl40']:.3f} "
            f"step=x{step} max={max(row):g}"
        )
    return "\n".join(lines)


if __name__ == "__main__":
    print(high_off_summary())
