"""Off `medium` — max-anchored geometric ladder (Keno Xtreme Medium / Crazy).

Same algorithm as Off `classic` (`easy_off_classic.generate_classic_row`):
lock the designed max, keep the HUD zero prefix, fill the body with a
constant-ratio ladder onto RTP 0.9650, snap to the 0.1x lattice, repair.

HUD pick 3 max 75x is 115% RTP and blows 2-Star ETL40 (0.80). Highest
in-window max with margin is 60.3x (etl40 0.732). 65.8x is the absolute
ETL40 ceiling (0.799) and is not shipped.

Pick 2: HUD 9.00 cannot land on-grid (1.1/9.0 = 0.9423 under; 1.1/9.4 =
0.965385). Same lattice exception as Classic 5.0→5.4.

Pick 4: HUD 175.0 has no legal progressive row; snap is 174.9.

pick_1 stays lattice [0.2, 3.2] with the miss-bonus third tier in
keno_pick_one.py (medium is still in PICK_ONE_BONUS_RISKS).

Scope: **Off only.** Earn `medium` and the buy chips keep their own ladders.
"""

from __future__ import annotations

from fractions import Fraction

from easy_off_classic import generate_classic_row
from keno_pick_one import MODE_RTP_BAND, STD_MIN, base_coeff, base_stats

RTP_WINDOW = (0.9630, 0.9655)
#: Local ETL40 cap — tighter than etl_sum 1.45; pick 3 is the binding row.
ETL40_CAP = 0.88

#: Competitor Medium HUD rows: zeros/shape template only.
MEDIUM_HUD = {
    2: [0.00, 0.95, 9.00],
    3: [0.00, 0.00, 1.75, 75.00],
    4: [0.00, 0.00, 0.95, 7.00, 175.0],
    5: [0.00, 0.00, 1.20, 3.00, 9.00, 450.0],
    6: [0.00, 0.00, 0.00, 1.50, 5.00, 50.00, 650.0],
    7: [0.00, 0.00, 0.00, 0.95, 3.00, 7.50, 90.00, 750.0],
    8: [0.00, 0.00, 0.00, 0.95, 2.00, 5.00, 15.00, 150.0, 2500.0],
    9: [0.00, 0.00, 0.00, 0.95, 1.10, 2.50, 5.00, 40.00, 350.0, 4000.0],
    10: [0.00, 0.00, 0.00, 0.50, 0.95, 1.50, 3.00, 9.00, 40.00, 400.0, 5000.0],
}

#: Designed max ladder. Strictly increasing from pick_1 lattice max 3.2.
#: Pick 2/3/4 cannot take the HUD tops (lattice / ETL40 / generator reject).
MAX_LADDER = {
    2: 9.4,
    3: 60.3,
    4: 174.9,
    5: 450.0,
    6: 650.0,
    7: 750.0,
    8: 2500.0,
    9: 4000.0,
    10: 5000.0,
}

#: Geometric lock replaces the restair `shape_lock` for this chart.
SHAPE_LOCKED: frozenset[int] = frozenset(range(2, 11))


def generate_medium_row(k: int) -> list[float]:
    return generate_classic_row(k, MEDIUM_HUD[k], MAX_LADDER[k])


def generate_medium_off() -> dict[int, list[float]]:
    return {k: generate_medium_row(k) for k in sorted(MEDIUM_HUD)}


#: Shipped Off `medium` chart (picks 2-10). Generated by the max-anchored
#: geometric ladder onto 0.9650. Pick 2 cannot hit 0.9650 exactly:
#: 1.1/9.4 = 0.965385 is the closest legal pair.
MEDIUM_OFF: dict[int, list[float]] = {
    2: [0.0, 1.1, 9.4],
    3: [0.0, 0.0, 1.7, 60.3],
    4: [0.0, 0.0, 0.7, 10.5, 174.9],
    5: [0.0, 0.0, 0.3, 3.9, 41.8, 450.0],
    6: [0.0, 0.0, 0.0, 2.6, 16.6, 103.8, 650.0],
    7: [0.0, 0.0, 0.0, 1.8, 8.1, 36.8, 165.3, 750.0],
    8: [0.0, 0.0, 0.0, 0.9, 4.4, 21.5, 104.5, 512.4, 2500.0],
    9: [0.0, 0.0, 0.0, 0.7, 2.6, 11.6, 51.0, 216.3, 932.9, 4000.0],
    10: [0.0, 0.0, 0.0, 0.5, 1.9, 7.1, 25.9, 97.3, 362.1, 1343.3, 5000.0],
}


def _exact_rtp(k: int, row: list[float]) -> Fraction:
    return sum(coeff * Fraction(str(m)) for coeff, m in zip(base_coeff(k), row))


def _validate() -> None:
    generated = generate_medium_off()
    prev_max = 3.2  # medium pick_1 lattice max
    for k, row in sorted(MEDIUM_OFF.items()):
        hud = MEDIUM_HUD[k]
        assert row == generated[k], (
            f"pick_{k}: baked MEDIUM_OFF {row} != generator {generated[k]}"
        )
        assert len(row) == k + 1, f"pick_{k}: row length {len(row)} != {k + 1}"
        for h, m in enumerate(row):
            assert m == 0.0 or abs(m * 10 - round(m * 10)) < 1e-9, (
                f"pick_{k} h={h}: {m} is off the 0.1x lattice"
            )
        assert [m == 0 for m in row] == [m == 0 for m in hud], (
            f"pick_{k}: zero prefix diverges from the Medium HUD shape"
        )
        paying = [m for m in row if m > 0]
        assert all(b > a for a, b in zip(paying, paying[1:])), (
            f"pick_{k}: ladder is not strictly increasing: {row}"
        )
        expected_max = MAX_LADDER[k]
        assert max(row) == expected_max, (
            f"pick_{k}: max {max(row)} != designed max {expected_max}"
        )
        assert max(row) > prev_max, (
            f"pick_{k}: max {max(row)} does not exceed previous max {prev_max}"
        )
        prev_max = max(row)
        rtp = _exact_rtp(k, row)
        lo, hi = MODE_RTP_BAND
        assert lo < rtp < hi, f"pick_{k}: rtp {float(rtp):.6f} outside band"
        assert RTP_WINDOW[0] <= rtp <= RTP_WINDOW[1], (
            f"pick_{k}: rtp {float(rtp):.6f} outside designed window "
            f"{RTP_WINDOW[0]:.4f}-{RTP_WINDOW[1]:.4f}"
        )
        stats = base_stats(k, row)
        assert stats["std"] >= STD_MIN, (
            f"pick_{k}: std {stats['std']:.3f} < {STD_MIN} (Base Mode STD floor)"
        )
        assert stats["hit_rate"] >= 0.021, f"pick_{k}: hit rate below 1 in 50"
        assert stats["etl_sum"] <= 1.45, f"pick_{k}: etl_sum over the 3-Star gate"
        assert stats["etl40"] <= ETL40_CAP, (
            f"pick_{k}: etl40 {stats['etl40']:.3f} over {ETL40_CAP}"
        )


_validate()


def medium_off_summary() -> str:
    lines = []
    for k, row in sorted(MEDIUM_OFF.items()):
        cells = " / ".join(f"{m:g}" for m in row if m > 0)
        rtp = float(_exact_rtp(k, row))
        stats = base_stats(k, row)
        pay = [m for m in row if m > 0]
        ratios = [b / a for a, b in zip(pay, pay[1:])]
        step = f"{min(ratios):.2f}-{max(ratios):.2f}" if ratios else "-"
        lines.append(
            f"medium_pick_{k:<2d} [{cells}] "
            f"rtp={rtp:.6f} edge={1 - rtp:.4%} "
            f"std={stats['std']:.3f} etl40={stats['etl40']:.3f} "
            f"step=x{step} max={max(row):g}"
        )
    return "\n".join(lines)


if __name__ == "__main__":
    print(medium_off_summary())
